#
# Makefile
#
# Makefile for macchina.io samples
#

.PHONY: clean all

clean all:
	$(MAKE) -C nanoleaf $(MAKECMDGOALS)
	$(MAKE) -C poco-dnssd $(MAKECMDGOALS)
	$(MAKE) -C poco-dnssd/Bonjour $(MAKECMDGOALS)
